public class ThreadState {
  
  // * STATES OF THREAD

  // * NEW STATE -> WHEN A THREAD IS INSTANTIATED

  // * RUNNABLE STATE -> WHEN A THREAD IS CALLED WITH A START METHOD t1.start()

  // * RUNNING STATE -> WHEN THE THREAD IS ACTUALLY RUNNING ON THE CPU t1.run()

// * WAITING STATE -> WHEN A STATE IS KEEP ON HOLD BY A WAIT METHOD t1.wait()


// * DEATH STATE -> WHEN A THREAD IS PUT TO DEATH WITH THE STOP METHOD t1.stop()


}
